dist: trusty

language: python
python:
  - 3.6

env:
  global:
    - PASS_VERSION=1.7

addons:
  apt:
    packages:
      - tree
      - xclip
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

before_script:
  - export PREFIX=$HOME/.bin/usr PATH="$PATH:$HOME/.bin/usr/bin"
  - wget https://git.zx2c4.com/password-store/snapshot/password-store-$PASS_VERSION.tar.xz
  - tar -xf password-store-$PASS_VERSION.tar.xz
  - make --directory=password-store-$PASS_VERSION install
  - pip install green coverage codacy-coverage

script:
  - make test

after_success:
  - cd tests && coverage xml
  - python-codacy-coverage -r coverage.xml

notifications:
  email: false
